// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function ApproveAgentAction(arg1, arg2) {
  return window['go']['main']['App']['ApproveAgentAction'](arg1, arg2);
}

export function CheckClaudeCLI() {
  return window['go']['main']['App']['CheckClaudeCLI']();
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function GetAgentMessages(arg1) {
  return window['go']['main']['App']['GetAgentMessages'](arg1);
}

export function GetAgentTasks(arg1) {
  return window['go']['main']['App']['GetAgentTasks'](arg1);
}

export function GetClaudeCLIVersion() {
  return window['go']['main']['App']['GetClaudeCLIVersion']();
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetMCPPresets() {
  return window['go']['main']['App']['GetMCPPresets']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetRecentProjects(arg1) {
  return window['go']['main']['App']['GetRecentProjects'](arg1);
}

export function GetSideBySideDiff(arg1) {
  return window['go']['main']['App']['GetSideBySideDiff'](arg1);
}

export function GetWorkspaceInfo(arg1) {
  return window['go']['main']['App']['GetWorkspaceInfo'](arg1);
}

export function IsOnboardingCompleted() {
  return window['go']['main']['App']['IsOnboardingCompleted']();
}

export function ListAgentSessions() {
  return window['go']['main']['App']['ListAgentSessions']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ParseDiff(arg1) {
  return window['go']['main']['App']['ParseDiff'](arg1);
}

export function RejectAgentAction(arg1, arg2) {
  return window['go']['main']['App']['RejectAgentAction'](arg1, arg2);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendAgentMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetPreferences(arg1) {
  return window['go']['main']['App']['SetPreferences'](arg1);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}
