// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function AddSessionTag(arg1, arg2) {
  return window['go']['main']['App']['AddSessionTag'](arg1, arg2);
}

export function ApproveAgentAction(arg1, arg2) {
  return window['go']['main']['App']['ApproveAgentAction'](arg1, arg2);
}

export function CheckClaudeCLI() {
  return window['go']['main']['App']['CheckClaudeCLI']();
}

export function CleanupOldSessions() {
  return window['go']['main']['App']['CleanupOldSessions']();
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function CreateAgentSession(arg1) {
  return window['go']['main']['App']['CreateAgentSession'](arg1);
}

export function CreateFirefighterSession(arg1, arg2) {
  return window['go']['main']['App']['CreateFirefighterSession'](arg1, arg2);
}

export function DeleteAgentSession(arg1) {
  return window['go']['main']['App']['DeleteAgentSession'](arg1);
}

export function GCloudGetAvailableProjects() {
  return window['go']['main']['App']['GCloudGetAvailableProjects']();
}

export function GCloudLogin() {
  return window['go']['main']['App']['GCloudLogin']();
}

export function GCloudLoginApplicationDefault() {
  return window['go']['main']['App']['GCloudLoginApplicationDefault']();
}

export function GCloudRevoke() {
  return window['go']['main']['App']['GCloudRevoke']();
}

export function GCloudSetProject(arg1) {
  return window['go']['main']['App']['GCloudSetProject'](arg1);
}

export function GCloudVerifyVertexAIAccess(arg1, arg2) {
  return window['go']['main']['App']['GCloudVerifyVertexAIAccess'](arg1, arg2);
}

export function GetAgentMessages(arg1) {
  return window['go']['main']['App']['GetAgentMessages'](arg1);
}

export function GetAgentMessagesPaginated(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAgentMessagesPaginated'](arg1, arg2, arg3);
}

export function GetAgentTasks(arg1) {
  return window['go']['main']['App']['GetAgentTasks'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetArchiveOldMessages() {
  return window['go']['main']['App']['GetArchiveOldMessages']();
}

export function GetAutoCleanupSessions() {
  return window['go']['main']['App']['GetAutoCleanupSessions']();
}

export function GetClaudeCLIVersion() {
  return window['go']['main']['App']['GetClaudeCLIVersion']();
}

export function GetFirefighterMonitorStatus(arg1) {
  return window['go']['main']['App']['GetFirefighterMonitorStatus'](arg1);
}

export function GetGCloudAuthInfo() {
  return window['go']['main']['App']['GetGCloudAuthInfo']();
}

export function GetGitDiff(arg1, arg2) {
  return window['go']['main']['App']['GetGitDiff'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GetKeepCompletedAgents() {
  return window['go']['main']['App']['GetKeepCompletedAgents']();
}

export function GetMCPPresets() {
  return window['go']['main']['App']['GetMCPPresets']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetMaxAgentsPerSession() {
  return window['go']['main']['App']['GetMaxAgentsPerSession']();
}

export function GetMaxMessagesPerSession() {
  return window['go']['main']['App']['GetMaxMessagesPerSession']();
}

export function GetMaxSessionAgeDays() {
  return window['go']['main']['App']['GetMaxSessionAgeDays']();
}

export function GetMaxTotalSessions() {
  return window['go']['main']['App']['GetMaxTotalSessions']();
}

export function GetOktaAccessToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOktaAccessToken'](arg1, arg2, arg3);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetRecentProjects(arg1) {
  return window['go']['main']['App']['GetRecentProjects'](arg1);
}

export function GetSessionStats() {
  return window['go']['main']['App']['GetSessionStats']();
}

export function GetSideBySideDiff(arg1) {
  return window['go']['main']['App']['GetSideBySideDiff'](arg1);
}

export function GetWorkspaceInfo(arg1) {
  return window['go']['main']['App']['GetWorkspaceInfo'](arg1);
}

export function InvestigateLinearTicket(arg1, arg2) {
  return window['go']['main']['App']['InvestigateLinearTicket'](arg1, arg2);
}

export function InvestigateSlackAlert(arg1, arg2, arg3) {
  return window['go']['main']['App']['InvestigateSlackAlert'](arg1, arg2, arg3);
}

export function IsFirefighterMonitoringActive(arg1) {
  return window['go']['main']['App']['IsFirefighterMonitoringActive'](arg1);
}

export function IsGCloudAuthenticated() {
  return window['go']['main']['App']['IsGCloudAuthenticated']();
}

export function IsGCloudInstalled() {
  return window['go']['main']['App']['IsGCloudInstalled']();
}

export function IsOktaAuthenticated(arg1, arg2, arg3) {
  return window['go']['main']['App']['IsOktaAuthenticated'](arg1, arg2, arg3);
}

export function IsOnboardingCompleted() {
  return window['go']['main']['App']['IsOnboardingCompleted']();
}

export function ListAgentSessions() {
  return window['go']['main']['App']['ListAgentSessions']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function OktaLogin(arg1, arg2, arg3) {
  return window['go']['main']['App']['OktaLogin'](arg1, arg2, arg3);
}

export function OktaRefreshToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['OktaRefreshToken'](arg1, arg2, arg3);
}

export function OktaRevoke(arg1, arg2, arg3) {
  return window['go']['main']['App']['OktaRevoke'](arg1, arg2, arg3);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ParseDiff(arg1) {
  return window['go']['main']['App']['ParseDiff'](arg1);
}

export function RejectAgentAction(arg1, arg2) {
  return window['go']['main']['App']['RejectAgentAction'](arg1, arg2);
}

export function RemoveMCPServer(arg1) {
  return window['go']['main']['App']['RemoveMCPServer'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['main']['App']['RemoveProject'](arg1);
}

export function RemoveSessionTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveSessionTag'](arg1, arg2);
}

export function SearchSessions(arg1) {
  return window['go']['main']['App']['SearchSessions'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendAgentMessage(arg1, arg2) {
  return window['go']['main']['App']['SendAgentMessage'](arg1, arg2);
}

export function SendNotification(arg1, arg2) {
  return window['go']['main']['App']['SendNotification'](arg1, arg2);
}

export function SetPreferences(arg1) {
  return window['go']['main']['App']['SetPreferences'](arg1);
}

export function SetSessionFavorite(arg1, arg2) {
  return window['go']['main']['App']['SetSessionFavorite'](arg1, arg2);
}

export function StartAgentSession(arg1) {
  return window['go']['main']['App']['StartAgentSession'](arg1);
}

export function StartFirefighterMonitoring(arg1) {
  return window['go']['main']['App']['StartFirefighterMonitoring'](arg1);
}

export function StopAgentSession(arg1) {
  return window['go']['main']['App']['StopAgentSession'](arg1);
}

export function StopFirefighterMonitoring(arg1) {
  return window['go']['main']['App']['StopFirefighterMonitoring'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}
