// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {main} from '../models';
import {agent} from '../models';
import {config} from '../models';
import {project} from '../models';
import {diff} from '../models';

export function AddMCPServer(arg1:mcp.Server):Promise<void>;

export function AddSessionTag(arg1:string,arg2:string):Promise<void>;

export function ApproveAgentAction(arg1:string,arg2:string):Promise<void>;

export function CheckClaudeCLI():Promise<boolean>;

export function CleanupOldSessions():Promise<number>;

export function CompleteOnboarding():Promise<void>;

export function CreateAgentSession(arg1:string):Promise<main.AgentSessionInfo>;

export function CreateFirefighterSession(arg1:string,arg2:string):Promise<main.AgentSessionInfo>;

export function DeleteAgentSession(arg1:string):Promise<void>;

export function GCloudGetAvailableProjects():Promise<Array<string>>;

export function GCloudLogin():Promise<void>;

export function GCloudLoginApplicationDefault():Promise<void>;

export function GCloudRevoke():Promise<void>;

export function GCloudSetProject(arg1:string):Promise<void>;

export function GCloudVerifyVertexAIAccess(arg1:string,arg2:string):Promise<void>;

export function GetAgentMessages(arg1:string):Promise<Array<agent.Message>>;

export function GetAgentMessagesPaginated(arg1:string,arg2:number,arg3:number):Promise<main.MessagePage>;

export function GetAgentTasks(arg1:string):Promise<Array<agent.Task>>;

export function GetAllTags():Promise<Array<string>>;

export function GetArchiveOldMessages():Promise<boolean>;

export function GetAutoCleanupSessions():Promise<boolean>;

export function GetClaudeCLIVersion():Promise<string>;

export function GetFirefighterMonitorStatus(arg1:string):Promise<Record<string, any>>;

export function GetGCloudAuthInfo():Promise<Record<string, any>>;

export function GetGitDiff(arg1:string,arg2:string):Promise<string>;

export function GetGitStatus(arg1:string):Promise<main.GitStatus>;

export function GetKeepCompletedAgents():Promise<boolean>;

export function GetMCPPresets():Promise<Array<mcp.Server>>;

export function GetMCPServers():Promise<Array<mcp.Server>>;

export function GetMaxAgentsPerSession():Promise<number>;

export function GetMaxMessagesPerSession():Promise<number>;

export function GetMaxSessionAgeDays():Promise<number>;

export function GetMaxTotalSessions():Promise<number>;

export function GetOktaAccessToken(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPreferences():Promise<config.UserPreferences>;

export function GetProject(arg1:string):Promise<project.Project>;

export function GetRecentProjects(arg1:number):Promise<Array<project.Project>>;

export function GetSessionStats():Promise<Record<string, any>>;

export function GetSideBySideDiff(arg1:diff.FileDiff):Promise<Array<diff.SideBySideLine>>;

export function GetWorkspaceInfo(arg1:string):Promise<project.WorkspaceInfo>;

export function IsFirefighterMonitoringActive(arg1:string):Promise<boolean>;

export function IsGCloudAuthenticated():Promise<boolean>;

export function IsGCloudInstalled():Promise<boolean>;

export function IsOktaAuthenticated(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function IsOnboardingCompleted():Promise<boolean>;

export function ListAgentSessions():Promise<Array<main.AgentSessionInfo>>;

export function ListProjects():Promise<Array<project.Project>>;

export function OktaLogin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OktaRefreshToken(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OktaRevoke(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenProject(arg1:string):Promise<project.Project>;

export function ParseDiff(arg1:string):Promise<Array<diff.FileDiff>>;

export function RejectAgentAction(arg1:string,arg2:string):Promise<void>;

export function RemoveMCPServer(arg1:string):Promise<void>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveSessionTag(arg1:string,arg2:string):Promise<void>;

export function SearchSessions(arg1:main.SearchSessionsRequest):Promise<Array<main.SearchSessionsResponse>>;

export function SelectFolder():Promise<string>;

export function SendAgentMessage(arg1:string,arg2:string):Promise<void>;

export function SendNotification(arg1:string,arg2:string):Promise<void>;

export function SetPreferences(arg1:config.UserPreferences):Promise<void>;

export function SetSessionFavorite(arg1:string,arg2:boolean):Promise<void>;

export function StartAgentSession(arg1:string):Promise<void>;

export function StartFirefighterMonitoring(arg1:string):Promise<void>;

export function StopAgentSession(arg1:string):Promise<void>;

export function StopFirefighterMonitoring(arg1:string):Promise<void>;

export function UpdateMCPServer(arg1:mcp.Server):Promise<void>;
